services:
  - type: web
    name: swasthya-api
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: OPENAI_API_KEY
        sync: false   # 🔐 Don't sync secrets to repo

    plan: free  # Or change to 'starter'/'pro' depending on Render plan
    autoDeploy: true  # Optional: redeploys on push to main branch
